// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Rentos.Models;
using System;

namespace Rentos.Migrations
{
    [DbContext(typeof(RentosContext))]
    [Migration("20180424102557_rentchange")]
    partial class rentchange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rentos.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<bool>("IsAvailable");

                    b.Property<string>("Manufacturer");

                    b.Property<int>("Mileage");

                    b.Property<string>("Model");

                    b.Property<string>("Picture");

                    b.Property<int>("Power");

                    b.Property<int>("Price");

                    b.Property<string>("RegistrationNumber");

                    b.HasKey("CarId");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Rentos.Models.Rent", b =>
                {
                    b.Property<int>("RentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CarId");

                    b.Property<int>("Car_CarId");

                    b.Property<DateTime>("DropoffDate");

                    b.Property<DateTime>("PickupDate");

                    b.Property<string>("User_UserId");

                    b.HasKey("RentId");

                    b.HasIndex("CarId");

                    b.ToTable("Rent");
                });

            modelBuilder.Entity("Rentos.Models.Rent", b =>
                {
                    b.HasOne("Rentos.Models.Car")
                        .WithMany("Rents")
                        .HasForeignKey("CarId");
                });
#pragma warning restore 612, 618
        }
    }
}
